### ISSUE TITLE
Error while invoking any command

### ISSUE THREAD

**Issue by rkapoz-tech** [12joan/please#2]
Hi, I installed ruby 3.1.2 on my UBUNTU 20.04, and followed your instructions to setup "please", but I receive this error

`❯ please find all files larger than 1 mb
/home/roby/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ruby-openai-3.0.2/lib/ruby/openai/client.rb:10:in `completions': unknown keyword: :engine (ArgumentError)
	from /home/roby/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/openai-please-0.1.3/lib/please/openai/codex_service.rb:11:in `completion'
	from /home/roby/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/openai-please-0.1.3/lib/please/request.rb:6:in `send'
	from /home/roby/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/openai-please-0.1.3/lib/please/cli.rb:91:in `<top (required)>'
	from <internal:/home/roby/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/home/roby/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/roby/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/openai-please-0.1.3/exe/please:4:in `<top (required)>'
	from /home/roby/.rbenv/versions/3.1.2/bin/please:25:in `load'
	from /home/roby/.rbenv/versions/3.1.2/bin/please:25:in `<main>'
`

**Comment by 12joan** [comment]
Thanks for the bug report! I had mistakenly used `>=` in the gem spec instead of `~>`.

Should be fixed in version 0.2.0. Can someone confirm it's working?
